theme: minima
title: Welcome to My Blog
author: Shivani Joshi
email: shivanijoshi2106@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I plan to talk about Data science here.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Shivani-joshi-21 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
